name: .NET6

on:
  push:
    branches: [ net6 ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
        
    - name: Build
      run: dotnet build ./BlazorWasmWithAADAuth/BlazorWasmWithAADAuth.sln --configuration Release
    - name: dotnet publish
      run: dotnet publish ./BlazorWasmWithAADAuth/BlazorWasmWithAADAuth.sln --self-contained true --runtime linux-x64 -c Release -o ${{env.DOTNET_ROOT}}/myapp
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'testnet2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_DEPLOY2 }}
        package: ${{env.DOTNET_ROOT}}/myapp 
